In [2]:
import pandas as pd
import numpy as np
df_1 = pd.DataFrame(
    {'month':np.arange(0, 6, 1),
     'value':np.random.randn(6) ,
     'who':'Bob'
    }    
)

df_2 = pd.DataFrame(
    {'month':np.arange(0, 6, 1),
     'value':np.random.randn(6) ,
     'who':'Alice'
    }    
)

df = pd.concat([df_1, df_2])

df = df.reset_index(drop=True)

In [3]:
#这种做法如果月份数据有丢失,会自然的比较连续的2条数据
df['previous'] = df.groupby('who')['value'].shift(1)
df['percentage'] = (df.value-df.previous )/df.previous
df

    month     value    who  previous  percentage
0       0 -1.857188    Bob       NaN         NaN
1       1  1.464422    Bob -1.857188   -1.788516
2       2 -2.692063    Bob  1.464422   -2.838311
3       3 -0.538969    Bob -2.692063   -0.799793
4       4 -1.510322    Bob -0.538969    1.802243
5       5  0.344021    Bob -1.510322   -1.227780
6       0 -0.325872  Alice       NaN         NaN
7       1  2.156642  Alice -0.325872   -7.618067
8       2 -0.849840  Alice  2.156642   -1.394057
9       3 -0.609625  Alice -0.849840   -0.282658
10      4 -0.078461  Alice -0.609625   -0.871297
11      5  1.286209  Alice -0.078461  -17.393014